# Generated by Django 5.0.2 on 2026-02-22 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_add_surge_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('rating', models.PositiveSmallIntegerField(help_text='تقييم من 1 إلى 5', verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, default='', verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'db_table': 'visits_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='estimatelog',
            new_name='visits_esti_request_09d253_idx',
            old_name='visits_est_request_time_idx',
        ),
        migrations.RenameIndex(
            model_name='estimatelog',
            new_name='visits_esti_service_43d015_idx',
            old_name='visits_est_service_type_idx',
        ),
        migrations.AlterField(
            model_name='estimatelog',
            name='request_time',
            field=models.DateTimeField(db_index=True, help_text='وقت طلب التسعير', verbose_name='وقت الطلب'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text='نوع الخدمة التمريضية المطلوبة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='visits.servicetype', verbose_name='نوع الخدمة'),
        ),
        migrations.AddField(
            model_name='review',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='visits.visit', verbose_name='الزيارة'),
        ),
    ]
