# Generated by Django 5.0.2 on 2026-03-01 19:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_nurseprofile_syndicate_number_and_more'),
        ('visits', '0007_visit_agency_visit_distance_km_visit_distance_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='agency_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='take_rate_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='take_rate_percent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='users.agencyprofile', verbose_name='الوكالة'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='agency_payout',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مبلغ الوكالة'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ المدفوع'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paymob_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف الطلب في Paymob'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paymob_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف المعاملة في Paymob'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسوية'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wateen_take_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة المنصة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('ESCROWED', 'في الضمان'), ('SETTLED', 'تمت التسوية'), ('REFUNDED', 'تم الاسترجاع')], default='ESCROWED', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='visits.visit', verbose_name='الزيارة'),
        ),
    ]
