# Generated by Django 5.0.2 on 2026-03-01 22:18

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0009_enforce_transaction_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='المسافة بالكيلومتر', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المسافة بالكيلومتر'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='distance_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سعر الكيلومتر', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الكيلومتر'),
        ),
    ]
