# Generated by Django 5.0.2 on 2026-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_alter_visit_distance_km_alter_visit_distance_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='expected_duration',
            field=models.PositiveIntegerField(default=60, help_text='المدة الزمنية المتوقعة لتقديم الخدمة بالدقائق', verbose_name='المدة المتوقعة (بالدقائق)'),
        ),
    ]
