# Generated by Django 5.0.2 on 2026-02-16 16:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nurse_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('national_id_document', models.CharField(blank=True, default='', max_length=50, verbose_name='رقم الهوية المهنية')),
                ('syndicate_number', models.CharField(blank=True, default='', max_length=50, verbose_name='رقم النقابة')),
                ('syndicate_expiry', models.DateField(blank=True, null=True, verbose_name='انتهاء عضوية النقابة')),
                ('specializations', models.JSONField(blank=True, default=list, verbose_name='التخصصات')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='التقييم')),
                ('is_available', models.BooleanField(default=False, verbose_name='متاح')),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='آخر موقع')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='حالة التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ملف الممرض/ة',
                'verbose_name_plural': 'ملفات الممرضين',
                'db_table': 'users_nurse_profile',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='', max_length=10, verbose_name='الجنس')),
                ('address_text', models.TextField(blank=True, default='', verbose_name='العنوان')),
                ('home_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='موقع المنزل')),
                ('medical_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات طبية')),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=15, verbose_name='رقم الطوارئ')),
                ('wearables_enabled', models.BooleanField(default=False, verbose_name='أجهزة قابلة للارتداء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ملف المريض',
                'verbose_name_plural': 'ملفات المرضى',
                'db_table': 'users_patient_profile',
            },
        ),
    ]
