# Generated by Django 5.0.2 on 2026-03-01 12:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_refactor_userrole_enum'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('manager_name', models.CharField(max_length=255, verbose_name='اسم المدير')),
                ('commercial_registry', models.CharField(max_length=100, unique=True, verbose_name='السجل التجاري')),
                ('moh_license_number', models.CharField(max_length=100, unique=True, verbose_name='رقم ترخيص وزارة الصحة')),
                ('tax_id', models.CharField(max_length=100, unique=True, verbose_name='البطاقة الضريبية')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('verified', 'موثق'), ('suspended', 'موقوف'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('coverage_polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='نطاق التغطية')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='التقييم')),
                ('network_capacity', models.PositiveIntegerField(default=0, verbose_name='سعة الشبكة (عدد الممرضين)')),
                ('dispatch_mode', models.CharField(choices=[('AUTO', 'آلي'), ('MANUAL', 'يدوي')], default='AUTO', max_length=10, verbose_name='آلية التوزيع')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد المحفظة')),
                ('stripe_account_id', models.CharField(blank=True, help_text='Stripe Connect Account ID for payouts', max_length=100, null=True, verbose_name='معرف حساب سترايب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ملف الشركة/الوكالة',
                'verbose_name_plural': 'ملفات الشركات/الوكالات',
                'db_table': 'users_agency_profile',
                'indexes': [models.Index(fields=['status'], name='users_agenc_status_d68bed_idx'), models.Index(fields=['rating'], name='users_agenc_rating_560dc3_idx')],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='الشركة التابع لها المستخدم (للمديرين)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='users.agencyprofile', verbose_name='الشركة/الوكالة'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to='users.agencyprofile', verbose_name='الشركة/الوكالة التابع لها'),
        ),
        migrations.CreateModel(
            name='NurseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'بطاقة الرقم القومي'), ('SYNDICATE_CARD', 'كارنيه النقابة')], max_length=20, verbose_name='نوع المستند')),
                ('document_file', models.FileField(upload_to=users.models.kyc_document_upload_path, verbose_name='ملف المستند')),
                ('ocr_data', models.JSONField(blank=True, default=dict, help_text='البيانات المستخرجة من المستند عبر OCR', verbose_name='بيانات OCR')),
                ('extracted_national_id', models.CharField(blank=True, default='', help_text='الرقم القومي المكوّن من 14 رقم المستخرج من الصورة', max_length=14, verbose_name='الرقم القومي المستخرج')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('VERIFIED', 'تم التحقق'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=10, verbose_name='الحالة')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='سبب الرفض')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.nurseprofile', verbose_name='الممرض/ة')),
            ],
            options={
                'verbose_name': 'مستند الممرض/ة',
                'verbose_name_plural': 'مستندات الممرضين',
                'db_table': 'users_nurse_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='nursedocument',
            constraint=models.UniqueConstraint(fields=('nurse', 'document_type'), name='unique_nurse_document_type'),
        ),
    ]
