# Generated by Django 5.2.11 on 2026-03-01 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_agencyprofile_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('ACCEPTED', 'مقبول'), ('EXPIRED', 'منتهي الصلاحية')], default='PENDING', max_length=15, verbose_name='الحالة')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'دعوة ممرض/ة',
                'verbose_name_plural': 'دعوات الممرضين',
                'db_table': 'users_nurse_invitation',
            },
        ),
        migrations.RenameIndex(
            model_name='agencyprofile',
            new_name='users_agenc_coverag_703ce7_gist',
            old_name='users_agenc_coverag_bb79fd_gist',
        ),
        migrations.AddField(
            model_name='nurseinvitation',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.agencyprofile', verbose_name='الوكالة'),
        ),

        migrations.AddIndex(
            model_name='nurseinvitation',
            index=models.Index(fields=['status'], name='users_nurse_status_354f07_idx'),
        ),
    ]
