# Generated by Django 5.0.2 on 2026-03-02 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_kycauditlog_kycdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycauditlog',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'موافقة'), ('REJECT', 'رفض'), ('RESUBMIT', 'إعادة تقديم')], help_text='APPROVE, REJECT, or RESUBMIT', max_length=50, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='kycauditlog',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_audit_logs', to='users.agencyprofile', verbose_name='الشركة/الوكالة'),
        ),
    ]
