# Generated by Django 5.0.2 on 2026-02-17 07:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_nurseprofile_verification_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('MATCHED', 'تم المطابقة'), ('ACCEPTED', 'مقبولة'), ('ON_WAY', 'في الطريق'), ('ARRIVED', 'وصل'), ('IN_PROGRESS', 'جارية'), ('COMPLETED', 'مكتملة'), ('CANCELLED', 'ملغاة')], db_index=True, default='PENDING', max_length=15, verbose_name='الحالة')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='الموقع الجغرافي للمريض عند طلب الزيارة', srid=4326, verbose_name='موقع الزيارة')),
                ('service_type', models.CharField(blank=True, default='', help_text='نوع الخدمة التمريضية المطلوبة', max_length=50, verbose_name='نوع الخدمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='users.nurseprofile', verbose_name='الممرض/ة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='users.patientprofile', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
                'db_table': 'visits_visit',
                'ordering': ['-created_at'],
            },
        ),
    ]
