# Generated by Django 5.0.2 on 2026-03-01 19:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_nurseprofile_syndicate_number_and_more'),
        ('visits', '0006_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='users.agencyprofile', verbose_name='الشركة/الوكالة المنفذة'),
        ),
        migrations.AddField(
            model_name='visit',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='المسافة بالكيلومتر', max_digits=6, null=True, verbose_name='المسافة بالكيلومتر'),
        ),
        migrations.AddField(
            model_name='visit',
            name='distance_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سعر الكيلومتر', max_digits=10, null=True, verbose_name='سعر الكيلومتر'),
        ),
        migrations.AddField(
            model_name='visit',
            name='reroute_attempts',
            field=models.PositiveIntegerField(default=0, help_text='عدد محاولات إعادة توجيه الزيارة إلى وكالات أخرى', verbose_name='محاولات إعادة التوجيه'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='users.nurseprofile', verbose_name='الممرض/ة'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending_agency', 'في انتظار الوكالة'), ('pending_nurse', 'في انتظار الممرض'), ('accepted', 'مقبولة'), ('en_route', 'في الطريق'), ('in_progress', 'جارية'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], db_index=True, default='pending_agency', max_length=15, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف الدفع في سترايب')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي المبلغ')),
                ('take_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة المنصة')),
                ('take_rate_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مبلغ المنصة')),
                ('agency_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مبلغ الوكالة')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المعالجة'), ('ESCROWED', 'في الضمان'), ('SETTLED', 'تمت التسوية'), ('REFUNDED', 'تم الاسترجاع'), ('FAILED', 'فشلت')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='visits.visit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'عملية مالية',
                'verbose_name_plural': 'العمليات المالية',
                'db_table': 'visits_transaction',
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
