# Generated by Django 5.0.2 on 2026-03-09 12:00

from django.db import migrations

def seed_service_types(apps, schema_editor):
    ServiceType = apps.get_model('visits', 'ServiceType')
    services = [
        {"name": "General Nursing", "base_price": "200.00", "expected_duration": 60, "surge_multiplier": "1.00"},
        {"name": "Wound Care", "base_price": "150.00", "expected_duration": 30, "surge_multiplier": "1.20"},
        {"name": "IV Setup", "base_price": "120.00", "expected_duration": 45, "surge_multiplier": "1.10"},
    ]
    for service_data in services:
        ServiceType.objects.get_or_create(
            name=service_data["name"],
            defaults=service_data
        )

def reverse_seed(apps, schema_editor):
    ServiceType = apps.get_model('visits', 'ServiceType')
    ServiceType.objects.filter(name__in=["General Nursing", "Wound Care", "IV Setup"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_servicetype_expected_duration'),
    ]

    operations = [
        migrations.RunPython(seed_service_types, reverse_seed),
    ]
