# Generated by Django 5.0.2 on 2026-06-08 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_preferred_language'),
        ('visits', '0015_visit_nurse_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='routed_at',
            field=models.DateTimeField(blank=True, help_text='الوقت الذي تم فيه توجيه الزيارة إلى الوكالة الحالية', null=True, verbose_name='وقت التوجيه للوكالة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('ESCROWED', 'في الضمان'), ('SETTLED', 'تمت التسوية'), ('REFUNDED', 'تم الاسترجاع'), ('FAILED', 'فشل')], default='ESCROWED', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='users.nurseprofile', verbose_name='الممرض/ة'),
        ),
        migrations.CreateModel(
            name='DispatchOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('EXPIRED', 'منتهي الصلاحية')], default='PENDING', max_length=10)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='العرض ينتهي بعد 60 ثانية')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_offers', to='users.nurseprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_offers', to='visits.visit')),
            ],
            options={
                'ordering': ['-offered_at'],
                'indexes': [models.Index(fields=['visit', 'status'], name='visits_disp_visit_i_5c262d_idx'), models.Index(fields=['nurse', 'status'], name='visits_disp_nurse_i_5672b6_idx'), models.Index(fields=['expires_at'], name='visits_disp_expires_66951c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dispatchoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED')), fields=('visit',), name='unique_accepted_offer_per_visit'),
        ),
    ]
