"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from decouple import config, Csv
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured
from config.redis_utils import (
    get_redis_config,
    get_caches_config,
    get_channel_layers_config,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-dev-only-key-do-not-use-in-production"
    if config("DEBUG", default=False, cast=bool)
    else None,
)

if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is required in production"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())


# =============================================================================
# GDAL Configuration (Windows Compatibility)
# =============================================================================
def _configure_gdal():
    """Attempt to configure GDAL library path on Windows."""
    if os.name != "nt":
        return

    if os.environ.get("GDAL_LIBRARY_PATH"):
        return

    common_paths = [
        r"C:\OSGeo4W\bin\gdal304.dll",
        r"C:\OSGeo4W\bin\gdal303.dll",
        r"C:\OSGeo4W\bin\gdal302.dll",
        r"C:\Program Files\QGIS 3.28\bin\gdal304.dll",
        r"C:\Program Files\QGIS 3.34\bin\gdal304.dll",
        r"C:\Program Files (x86)\OSGeo4W\bin\gdal304.dll",
    ]

    for path in common_paths:
        if os.path.exists(path):
            os.environ["GDAL_LIBRARY_PATH"] = path
            return


_configure_gdal()

# Check GDAL availability after configuration
_GDAL_AVAILABLE = True
_GDAL_WARNING = None
if os.name == "nt" and not os.environ.get("GDAL_LIBRARY_PATH"):
    try:
        from osgeo import gdal
    except ImportError:
        _GDAL_AVAILABLE = False
        _GDAL_WARNING = (
            "\n"
            "======================================================================\n"
            "[WARN] GDAL NOT FOUND\n"
            "======================================================================\n"
            "\n"
            "GeoDjango requires GDAL but it was not found on your system.\n"
            "\n"
            "Options:\n"
            "  1. Install OSGeo4W from https://trac.osgeo.org/osgeo4w/\n"
            "  2. Set GDAL_LIBRARY_PATH environment variable\n"
            "  3. Run: python scripts/doctor.py\n"
            "======================================================================\n"
        )
        print(_GDAL_WARNING, file=sys.stderr)


# =============================================================================
# Redis Configuration (Hybrid Strategy)
# =============================================================================
_REDIS_CONFIG = get_redis_config(debug=DEBUG)

if _REDIS_CONFIG.backend_type == "redis":
    print(
        f"\n[OK] Connected to Cloud Redis ({_REDIS_CONFIG.latency_ms}ms latency)"
        f"\n     URL: {_REDIS_CONFIG.url_sanitized}\n",
        file=sys.stderr,
    )
elif _REDIS_CONFIG.backend_type == "locmem":
    if not DEBUG:
        raise ImproperlyConfigured(
            "Redis Required: REDIS_URL not configured and DEBUG=False.\n"
            "Configure REDIS_URL environment variable before deploying to production."
        )
    print(
        f"\n[WARN] Redis Unreachable. Using In-Memory Fallback (Dev Mode)"
        f"\n       Reason: {_REDIS_CONFIG.fallback_reason}"
        f"\n       Set REDIS_URL environment variable to enable Redis caching.\n",
        file=sys.stderr,
    )


# =============================================================================
# Application definition
# =============================================================================

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "users",
    "visits",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "config.asgi.application"

# Channel Layers configuration (hybrid Redis/InMemory)
CHANNEL_LAYERS = get_channel_layers_config(_REDIS_CONFIG)

# Cache configuration (hybrid Redis/LocMem)
CACHES = get_caches_config(_REDIS_CONFIG)

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL"),
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=False,  # Disabled for local development; enable for production
    )
}
# Enforce PostGIS engine for matching logic
DATABASES["default"]["ENGINE"] = "django.contrib.gis.db.backends.postgis"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]


# Media files (user-uploaded content: KYC documents, etc.)
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Maximum upload size: 10MB (suitable for ID document scans)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.CustomUser"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": config("JWT_SECRET_KEY", default=config("SECRET_KEY")),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ["rest_framework_simplejwt.tokens.AccessToken"],
    "TOKEN_TYPE_CLAIM": "token_type",
}

CSRF_TRUSTED_ORIGINS = [
    "https://wateen.live",
    "https://www.wateen.live",
]

CORS_ALLOW_CREDENTIALS = True

# CORS origins - configurable via environment variable for production
# Format: comma-separated URLs without spaces
# Example: CORS_ALLOWED_ORIGINS=https://example.com,https://www.example.com
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000",
    cast=Csv(),
)

# Additional CORS settings for production
CORS_ALLOW_ALL_ORIGINS = False  # Never allow all origins in production
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]

# =============================================================================
# Production Security Settings (applied only when DEBUG=False)
# =============================================================================
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

# =============================================================================
# Celery Configuration
# =============================================================================
_redis_url = config("REDIS_URL", default=None)

if DEBUG or _redis_url is None:
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"
else:
    CELERY_BROKER_URL = _redis_url
    CELERY_RESULT_BACKEND = _redis_url

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
