# Generated by Django 5.0.2 on 2026-02-16 09:01

import django.utils.timezone
import users.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='معرّف فريد للمستخدم', primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('national_id', models.CharField(db_index=True, help_text='الرقم القومي المصري - 14 رقم', max_length=14, unique=True, validators=[users.validators.validate_egyptian_national_id], verbose_name='الرقم القومي')),
                ('phone_number', models.CharField(help_text='رقم الهاتف المحمول - 11 رقم', max_length=15, unique=True, validators=[users.validators.validate_phone_number], verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, help_text='البريد الإلكتروني (اختياري)', max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin')], default='PATIENT', help_text='دور المستخدم في النظام', max_length=10, verbose_name='الدور')),
                ('first_name_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم الأول')),
                ('last_name_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='اسم العائلة')),
                ('is_active', models.BooleanField(default=True, help_text='تحديد ما إذا كان المستخدم نشطاً', verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, help_text='تحديد ما إذا كان المستخدم يمكنه الدخول لصفحة الإدارة', verbose_name='موظف')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'db_table': 'users_customuser',
                'ordering': ['-date_joined'],
            },
        ),
    ]
