# Generated by Django 5.0.2 on 2026-02-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nurseprofile_patientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('VERIFIED', 'موثق'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=10, verbose_name='حالة التحقق'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'ذكر'), ('FEMALE', 'أنثى')], default='', max_length=10, verbose_name='الجنس'),
        ),
    ]
