# Generated by Django 5.0.2 on 2026-03-01 19:26

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_nurseinvitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseprofile',
            name='syndicate_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='رقم النقابة'),
        ),
        migrations.AddIndex(
            model_name='nurseprofile',
            index=django.contrib.postgres.indexes.GistIndex(fields=['last_location'], name='users_nurse_last_lo_35fc41_gist'),
        ),
    ]
