# Generated by Django 5.0.2 on 2026-03-02 13:08

import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_nurseprofile_syndicate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('action', models.CharField(help_text='APPROVE or REJECT', max_length=50, verbose_name='الإجراء')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='متصفح المستخدم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإجراء')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_audit_logs', to='users.agencyprofile', verbose_name='الشركة/الوكالة')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
            ],
            options={
                'verbose_name': 'سجل تدقيق KYC',
                'verbose_name_plural': 'سجلات تدقيق KYC',
                'db_table': 'users_kyc_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('document_type', models.CharField(choices=[('COMMERCIAL_REGISTRY', 'السجل التجاري'), ('MOH_LICENSE', 'ترخيص وزارة الصحة'), ('TAX_ID', 'البطاقة الضريبية')], max_length=50, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to=users.models.agency_kyc_document_upload_path, verbose_name='الملف')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('version', models.IntegerField(default=1, verbose_name='الإصدار')),
                ('reviewer_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات المراجع')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='users.agencyprofile', verbose_name='الشركة/الوكالة')),
            ],
            options={
                'verbose_name': 'مستند الشركة/الوكالة (KYC)',
                'verbose_name_plural': 'مستندات الشركة/الوكالة (KYC)',
                'db_table': 'users_agency_kyc_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='kycdocument',
            constraint=models.UniqueConstraint(fields=('agency', 'document_type', 'version'), name='unique_agency_kyc_version'),
        ),
    ]
