# Generated by Django 5.0.2 on 2026-03-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_nurse_invitation_revoked_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nurseinvitation',
            name='users_nurse_status_354f07_idx',
        ),
        migrations.AddIndex(
            model_name='nurseinvitation',
            index=models.Index(fields=['agency', 'status'], name='users_nurse_agency__372848_idx'),
        ),
    ]
