# Generated by Django 5.0.2 on 2026-06-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_nurseinvitation_users_nurse_status_354f07_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', help_text='لغة الإشعارات المفضلة', max_length=5, verbose_name='اللغة المفضلة'),
        ),
    ]
