name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        env:
          GH_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          envs: GH_TOKEN
          script: |
            cd ~/-Wateen-
            git fetch https://oauth2:${GH_TOKEN}@github.com/azmyayman-maker/-Wateen-.git main
            git reset --hard FETCH_HEAD
            docker compose down --remove-orphans
            docker rm -f $(docker ps -a -q) || true
            docker network rm wateen_network || true
            docker compose up -d --build
